### PR TITLE
Build arm64 images in CI

### PR DESCRIPTION
**Pull request by harryzcy**

### CODE REVIEW

**Comment by pschiffe** [comment]
Awesome, could you update also the `docker-image-pr.yml` file? I'll be happy to merge.
BTW did you try it? I don't have any arm to check.

**Comment by harryzcy** [comment]
Building for arm would be super slow on GitHub actions, so I don't think it's good to run it for every PR.

For testing, I can compile PDNS and PDNS Recursor successfully. I'll do a bit more tests for other images.

**Comment by harryzcy** [comment]
Ok.. I tried to build them on arm64 via GitHub actions. The PDNS and PDNS Recursor are fine. The build for admin base is successful, but way too slow.

The build for admin uwsgi errored. I don't know if I have time to solve it though. I'm testing them in my [arm64-test-workflows](https://github.com/harryzcy/docker-pdns/tree/arm64-test-workflows) branch.

**Comment by pschiffe** [comment]
Hi @harryzcy . Thanks for your PR and  tests. In the end I went with just arm64 builds for pdns and recursor and not for the pdns-admin. The reason is that they've changed something recently and now the build of assets for arm won't even finish in 6 hours in Github CI. I will try to re-evaluate later if the situation changes.

The error you encountered is due to the fact, that the pdns-admin base image must be pushed to the registry before the uwsgi and static images can be build.

**Pull request merged**
