### PR TITLE
Include pdns-backend-pipe

### PR DESCRIPTION
**Pull request by TijZwa**

### CODE REVIEW

**Comment by pschiffe** [comment]
Thanks for the PR. Could you add the `pdns-backend-pipe` package also to the [Fedora based image](https://github.com/pschiffe/docker-pdns/blob/master/pdns/Dockerfile#L8), so the images are kept in sync?

Also, what's your use case for this backend?

**Comment by TijZwa** [comment]
Sorry for my late response!
The use case for this backend is the usage of a dynamic reverse zone backend, found at https://github.com/endreszabo/PowerDNS-Dynamic-Reverse-Backend

But, I found out the the following python modules needs to be installed: netaddr, py-radix, ipy, pyyaml.
I don't know if you want to include this modules in the docker images? If not, it might be a better idea for me to build a new layer on top of this image and close this PR.

**Comment by pschiffe** [comment]
No worries, thanks for the reply. Looking at that project, I'm afraid it would be too much deps and complexity added to this repo. Feel free to use this repo as a base for your images with this additional backend included and let me know once you have it working. Thanks!

**Comment by TijZwa** [comment]
Thanks!
I figured it out.
For reference, I've included the docker file below.

I'm using the following env variables:

      PDNS_launch: pipe,gmysql
      PDNS_pipe_command: /var/lib/powerdns/scripts/pdns-dynamic-reverse-backend.py
      PDNS_pipe_timeout: 500


```
FROM alpine:3.12

# Install packages
RUN apk add --no-cache \
    mariadb-client \
    pdns \
    pdns-backend-mysql \
    pdns-backend-pipe \
    pdns-doc \
    py3-pip \
    python3

# Install build dependencies, needed to build py-radix
RUN apk add --no-cache \
	build-base \ 
	python3-dev

# Install python modules
RUN pip3 install --no-cache-dir \
	envtpl \
	ipy \
	netaddr \
	py-radix \
	pyyaml

# PowerDNS variables
ENV VERSION=4.2 \
  PDNS_guardian=yes \
  PDNS_setuid=pdns \
  PDNS_setgid=pdns \
  PDNS_launch=gmysql

# Template files
COPY pdns.conf.tpl /
COPY docker-entrypoint.sh /

# Ensure the x permission on the docker-entrypoint
RUN chmod +x /docker-entrypoint.sh

# Entrypoint, as copied from pschiffe/docker-pdns (see README.md)
ENTRYPOINT [ "/docker-entrypoint.sh" ]
CMD [ "/usr/sbin/pdns_server" ]
```

**Pull request closed without merging**
