### PR TITLE
Introduce arm-builds, makefile and docker-compose, cleanup, docker standards/alignment

### PR DESCRIPTION
**Pull request by EugenMayer**
- Introduce build-matrix to support arm32v6/7 and arm64v8, use a template system for that, based on the `Dockerfile` (fedora) docker files
- add a `Makefile` to cope with that in a convenient way
- add `gomplate` for Dockerfile generation
- Document build in `README.md`
- Document `Dockerfile`s in `README.md`
- add `docker-compose.yml` to introduce a simple project startup and test full integrated
- Introduce Introduce MYSQL_ENV_MYSQL_HOST and MYSQL_ENV_MYSQL_PORT for uwsgi and pdns
- Introduce optional PDNS_ENV_PDNS_webserver_host for pdns-admin-uwsgi to define
the upstream pdns server webadmin hostname
- Migrated `docker-cmd.sh` to entrypoint and adjust the `Dockerfiles` to us `ENTRYPOINT` / `CMD` properly
- Start with the `ngoduykhanh` based build in a new Dockerfile (#12), still WIP
- remove old pdns-admin folder / build  which was disfunctional anyway
- remove the alpine builds due to the pip issues vs `apk add py-ldap` and so on, see comment

I did only touch the fedora based builds ( `Dockerfile` ) a little ( entrypoint migration ), then copied the Dockerfile (fedora based ) for php-admin-backend. All the others seem to work fine with  alpine 3.8

### CODE REVIEW

**Comment by EugenMayer** [comment]
That was basically my basic adjustment to make the project ready for arm and easy setup, i hope you like it

**Comment by EugenMayer** [comment]
Status is, the arm/amd builds are working fine for everything except
 -  `pdns-admin-uwsgi` (0x97 variant)
 -  `pdns-admin-static` (`ngoduykhanh` variant) - not tested could work
 -  `pdns-admin-uwsgi` (`ngoduykhanh` variant) - uwsgi  issues, not finished

**Comment by EugenMayer** [comment]
I ditched the `alpine` effort since alpine has issues with system-based installed python packages being available in pip. So `apk add py-mysqldb`will still lead to `pip list` not list the module. This is different for debian and fedora.

I picked up your fedora image and templated it. One thing i fixed is

```
: "${PDNS_ADMIN_PDNS_VERSION:='${PDNS_ENV_VERSION:-}'}"
```

if PDNS_ADMIN_PDNS_VERSION is not set, it will lead to an exception during the start.

**Comment by EugenMayer** [comment]
Ok that is now a finished setup with all arch builds and `pdns-admin-uwsgi on Fedora and every setup in `docker-compose.yml` and all the stuff in the description above.

Not finished/addressed here is the build of `ngoduykhanh` - but that does not need to, it's not "live" and its just a sidepath for now

 -  `pdns-admin-static` (`ngoduykhanh` variant) - not tested could work
 -  `pdns-admin-uwsgi` (`ngoduykhanh` variant) - uwsgi  issues, not finished

**Comment by pschiffe** [comment]
@EugenMayer please - what's the advantage of having the `docker-cmd.sh` as entrypoint instead of cmd?

**Comment by EugenMayer** [comment]
`docker run -it pschiffe/pdns-mysql bash`

Works right away. Its best practise and also lets you override the CMD, but not the entrypoint in overrding images.

**Comment by pschiffe** [comment]
OK, thanks. I just usually use `exec`, but this makes sense. I'm thinking I'll try to cherry pick your changes gradually, so I can easily test them. I'll have more stupid questions probably :-)

**Comment by EugenMayer** [comment]
what about just testing my branch

**Comment by pschiffe** [comment]
It is actually breaking something, at the first glance I see that it breaks automatic image building on docker hub, which currently expects Dockerfile and Dockerfile.alpine files. But no worries, I'll figure it out.

**Comment by pschiffe** [comment]
Hey @EugenMayer . I've included couple of your changes into my repo. The new variables, entrypoints and I also have working ngoduykhanh version of pdns admin. Now I have another question - is it possible to build alt arch images on docker hub and host them there?

**Pull request closed without merging**
